apiVersion: v1
data:
  CONNECTION_STRING: {{ tpl "Server={{ .Release.Name }}-sql,1433;Database=Master;User Id=SA;Password=unsafeP@ss831920133Ae33ggda" . | b64enc }}
  SA_PASSWORD: {{ "unsafeP@ss831920133Ae33ggda" | b64enc }}
  SETUP_SECRET: {{ "changeme" | b64enc }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-db
type: Opaque
