# Default values for redis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: bitnami/redis
  pullPolicy: IfNotPresent
  tag: "latest"
service:
  type: ClusterIP
  port: 6379