# Default values for redis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: microsoft/mssql-server-linux
  pullPolicy: IfNotPresent
  tag: "2017-latest"
service:
  type: ClusterIP
  port: 1433