apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-sql
  name: {{ .Release.Name }}-sql
spec:
  ports:
  - name: {{ .Values.service.port | quote }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-sql
