# Default values for redis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: davidaks.azurecr.io/containerchat-web
  pullPolicy: IfNotPresent
  tag: "latest"
service:
  type: LoadBalancer
  port: 80
resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"
