version: "3.2"
services:
  containerchat-sql:
    container_name: containerchat-sql
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      SA_PASSWORD: "unsafeP@ss831920133Ae33ggda"
      ACCEPT_EULA: "Y"
    command: /usr/share/sql/entrypoint.sh
    volumes:
      - ./entrypoint.sh:/usr/share/sql/entrypoint.sh
      - ./InitialSetup.sh:/usr/share/sql/InitialSetup.sh
      - ./InitialSetup.sql:/usr/share/sql/InitialSetup.sql
  containerchat-redis:
    container_name: containerchat-redis
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  containerchat-web:
    container_name: containerchat-web
    image: 'web'
    ports:
      - "8080:80"
    environment:
      - AppSettings__RedisConnectionString=containerchat-redis
      - AppSettings__SetupSecret=changeme
      - ConnectionStrings__DefaultConnection=Server=containerchat-sql,1433;Database=Master;User Id=SA;Password=unsafeP@ss831920133Ae33ggda
      - ElasticApm__ServerUrls=http://containerchat-apm:8200
      - ElasticApm__ServiceName=ContainerChat
    command: dotnet /app/web.dll
  containerchat-elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: containerchat-elastic
    environment:
      - node.name=containerchat-elastic
      - cluster.name=continerchat-es-cluster
      - discovery.type=single-node
        #- discovery.seed_hosts=es02,es03
        # - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  containerchat-kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    container_name: containerchat-kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://containerchat-elastic:9200
      ELASTICSEARCH_HOSTS: http://containerchat-elastic:9200
  containerchat-apm:
    image: docker.elastic.co/apm/apm-server:7.9.3
    container_name: containerchat-apm
    environment:
      - ESHOST=http://containerchat-elastic:9200
    command: "apm-server -e -E output.elasticsearch.hosts=$${ESHOST}"
