apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-web
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/success-codes: 200,302
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: {{ .Release.Name }}-web
              servicePort: 80

